title = "Free IT Solutions - online solutions for IT problems"
baseURL = "http://www.freeitsolutions.com/"
languageCode = "en-us"
theme = "airspace-hugo"
publishDir = "docs"

[menu]

  #[[menu.header]]
  #  weight = 2
  #  name = "Work"
  #  url = "/work"
  #[[menu.header]]
  #  weight = 3
  #  name = "Blog"
  #  url = "/blog"
  #[[menu.header]]
  #  weight = 4
  #  name = "Service"
  #  url = "/service"
  [[menu.header]]
    weight = 4
    name = "Photoshop"
    url = "/photoshop"
  [[menu.header]]
    weight = 5
    name = "SEO"
    url = "/seo"      
  [[menu.header]]
    weight = 6
    name = "Web Development"
    url = "/web-development"      
  [[menu.header]]
    weight = 7
    name = "Contact"
    url = "/contact"

  [[menu.footer]]
    weight = 1
    name = "About us"
    url = "#"
  [[menu.footer]]
    weight = 2
    name = "Contact us"
    url = "#"
  #[[menu.footer]]
  #  weight = 3
  #  name = "How it works"
  #  url = "#"
  #[[menu.footer]]
  #  weight = 4
  #  name = "Blog"
  #  url = "#"
  #[[menu.footer]]
  #  weight = 5
  #  name = "Terms"
  #  url = "#"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  date_format = "Monday, Jan 2, 2006"

  home = "Home"

  [params.slider]
    enable = true
    title = "Having an IT related problem?"
    subtitle = "For every problem there is a solution. We gather free online solutions for various problems and offer them to yo for free"

    [[params.slider.button]]
      label = "Photoshop Resources"
      url = "/photoshop/"

    [[params.slider.button]]
      label = "SEO Solutions"
      url = "/seo/"

    [[params.slider.button]]
      label = "Web Development Solutions"
      url = "/web-development/"

  [params.wrapper]
    enable = true
    title = "About Us"
    italic = "Web developers, programmers, graphic and web designers"
    paragraph = "Wouldn't it be nice to have all your favorite online tools in one place? We are IT, free IT solutions"

  [params.blog]
    enable = true
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

  [params.photoshop]
    enable = true
    title = "Photoshop Resources"
    subtitle = "Here's a list of Photoshop resources you can use for free"

  [params.seo]
    enable = true
    title = "Online SEO Tools"
    subtitle = "Here's a list of online SEO tools that you can use for free"

  [params.web-development]
    enable = true
    title = "Web Development Free Solutions"
    subtitle = "Here's a list of online web development solutions that you can use for free"    

  [params.feature]
    enable = true
    title = "We believe in great ideas"
    content = "Always looking for top notch online tools. We think that the internet is your friend. It's filled with usefull online tools for various problems. We are trying to collect these nuggets and provide them to you in only one place"
    [params.feature.button]
      caption = "View Works"
      url = "#"

  [params.call]
    enable = true
    title = "Free IT Solutions"
    paragraph = "For every problem there is a solution. We gather free online solutions for various problems and offer them to yo for free"

  [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "Donâ€™t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Stop by for a visit"
      address = "North Main Street, Brooklyn Australia"
      email = "Email: info@freeitsolutions.com.com"
      phone = ""
    [params.contact.gmaps]
      title = "We Also Count in Google Maps"
      
  [params.publisher]
    name = "FreeITSolutions.com"

    [params.publisher.logo]
      url = "/img/logo.png"
      width = 151
      height = 41

  [params.logo]
    url = "/img/logo.png"
    width = 151
    height = 41

[params.google]
  analytics="UA-1211822-1"